name: controller
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^1.0.4
  supabase_flutter: ^0.3.3
  pedantic_mono: ^1.19.2
  window_manager: ^0.2.5
  json_annotation: ^4.6.0
  toggle_switch: ^2.0.1
  cool_alert: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/category_logo/
    - assets/
